apiVersion: v1
kind: Service
metadata:
  name: intern-starter-app
  namespace: test
  labels:
    app: intern-starter-app
spec:
  selector:
    app: intern-starter-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
